# Trigger build
name = "smart-task-frontend"
compatibility_date = "2024-04-03"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "brandy-3d-db"
database_id = "efc3cd4d-86b6-4101-ab5a-7b3466446dbb"
