// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/16/2026, 1:42:22 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/plugins/**/*.{js,ts,mjs}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/composables/**/*.{js,ts,mjs}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/utils/**/*.{js,ts,mjs}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/app.config.{js,ts,mjs}","C:/Users/ShongYi/Documents/Proyectos/Task-Manager/smart-task-frontend/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;